{
  "comments": [
    {
      "key": {
        "uuid": "a1d351d1_9e7f457a",
        "filename": "src/add-ons/kernel/network/protocols/tcp/EndpointManager.cpp",
        "patchSetId": 8
      },
      "lineNbr": 275,
      "author": {
        "id": 1000024
      },
      "writtenOn": "2020-01-31T19:43:04Z",
      "side": 1,
      "message": "The wording seems odd, should the \"connect\" be removed?",
      "revId": "70f097f40e1d6fff596c7dd7a12df03b2481e409",
      "serverId": "40b9299a-d8a8-485d-9b01-e6d3f45eefb5",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "1d4d899d_7e63a826",
        "filename": "src/add-ons/kernel/network/protocols/tcp/EndpointManager.cpp",
        "patchSetId": 8
      },
      "lineNbr": 292,
      "author": {
        "id": 1000024
      },
      "writtenOn": "2020-01-31T19:43:04Z",
      "side": 1,
      "message": "I am just wondering why the endpoint can be already in fConnectionHash at this point? Why is the endpoint not removed from the hash when the remote is not accepting the connection?",
      "revId": "70f097f40e1d6fff596c7dd7a12df03b2481e409",
      "serverId": "40b9299a-d8a8-485d-9b01-e6d3f45eefb5",
      "unresolved": true
    }
  ]
}